version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./production-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/smartagent.rocks/fullchain.pem:/etc/letsencrypt/live/smartagent.rocks/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/smartagent.rocks/privkey.pem:/etc/letsencrypt/live/smartagent.rocks/privkey.pem
